# Generated by Django 4.2.2 on 2023-06-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Имя пользователя', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя', max_length=150)),
                ('email', models.EmailField(help_text='Email пользователя', max_length=254, null=True, unique=True)),
                ('password', models.CharField(help_text='Пароль пользователя', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Телефон пользователя', max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь')], default='user', help_text='Роль пользователя', max_length=15)),
                ('image', models.ImageField(help_text='Фото пользователя', null=True, upload_to='images/')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли пользователь')),
                ('last_login', models.DateTimeField(auto_now_add=True, help_text='Дата последней авторизации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
